[package]
name = "pktreplay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
luomu-libpcap = {git= "https://github.com/sensorfu/luomu-libpcap", rev="7eddc07f7a49105d95ce8cc2506fee13af00b4d0"}
anyhow = { version = "1"}
env_logger = {version= "^0.9"}
log = {version="^0.4"}
clap = {version="^3.0"}
signal-hook = {version="^0.3"}
